### ISSUE TITLE
Installation issue - module 'django.contrib.gis.admin' has no attribute 'OSMGeoAdmin'

### ISSUE THREAD

**Issue by bzhangjma** [opennorth/represent-boundaries#47]
Hello,

I am experiencing an issue when installing the project following the steps here: https://opennorth.github.io/represent-boundaries-docs/docs/install/

Executing Step 7. `python manage.py migrate` gives: `AttributeError: module 'django.contrib.gis.admin' has no attribute 'OSMGeoAdmin'`

`pip list` gives
```
Package              Version
-------------------- -------
asgiref              3.8.1
Django               5.1.3
django-appconf       1.0.6
pip                  24.2
psycopg2             2.9.10
represent-boundaries 0.10.2
sqlparse             0.5.2
```
I am using Python 3.13.0 on Mac OS 14.5. The full traceback:
```
Traceback (most recent call last):
  File "/Users/XXX/represent-boundaries/my_project/manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "/Users/XXX/represent-boundaries/my_project/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/XXX/represent-boundaries/venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/Users/XXX/represent-boundaries/venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
    ~~~~~~~~~~~~^^
  File "/Users/XXX/represent-boundaries/venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/represent-boundaries/venv/lib/python3.13/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/XXX/represent-boundaries/venv/lib/python3.13/site-packages/django/contrib/admin/apps.py", line 27, in ready
    self.module.autodiscover()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/XXX/represent-boundaries/venv/lib/python3.13/site-packages/django/contrib/admin/__init__.py", line 52, in autodiscover
    autodiscover_modules("admin", register_to=site)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/represent-boundaries/venv/lib/python3.13/site-packages/django/utils/module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/XXX/represent-boundaries/venv/lib/python3.13/site-packages/boundaries/admin.py", line 12, in <module>
    class BoundaryAdmin(admin.OSMGeoAdmin):
                        ^^^^^^^^^^^^^^^^^
AttributeError: module 'django.contrib.gis.admin' has no attribute 'OSMGeoAdmin'
```

I did notice `Represent Boundaries requires Python 2.6, 2.7, 3.3 or 3.4`. Unfortunately after much hassle the earliest Python version I could install was 3.5 which still gives me the same error. I appreciate your guidance.

**Comment by jpmckinney** [comment]
The package is tested on Python 3.8 to 3.12, and Django 3.2 to 4.2. You installed Django 5.1, which is untested (and probably doesn't work). Only Django LTS are supported (so when 5.2 comes out, support will be added).

Why are you installing this package anyway? I thought the work was on scrapers-ca?

**Comment by bzhangjma** [comment]
Thank you James. Nunavut recently published GIS files of their electoral districts found here https://www.elections.nu.ca/en/documents, and I am interested in uploading those to represent. 

Also it seems Nunavut scrapper already exists `https://github.com/opencivicdata/scrapers-ca/tree/master/ca_nu`.

**Comment by jpmckinney** [comment]
I will add the shapefiles when I have a moment.
